nameOverride: ""
fullnameOverride: ""

replicas: 3

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

minReadySeconds: 10

image:
  repository: europe-west4-docker.pkg.dev
  name: kitae-seo-wiremind-test/hello-repo/hello-app
  tag: HELLO_TAG
  pullPolicy: IfNotPresent
  extraAnnotations: {}

service:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

lifecycle:
  preStop:
    exec:
      command: ["sleep", "15"]

port: 8080

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

podSecurityContext: {}

securityContext: {}

ingress: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
